### ISSUE TITLE
Put Object(s)

### ISSUE THREAD

**Issue by trajche** [digitalnodecom/node-red-contrib-generic-s3#10]
Would be awesome to be able to feed an array and have the Node create multiple objects from it. Ideally this array could contain keys, body, meta (all the same as Put Object).

**Comment by rristov60** [comment]
This feature has been added in the newest release [1.1.0](https://github.com/digitalnodecom/node-red-contrib-generic-s3/releases/tag/1.1.0). This release adds **Put Objects** node which allows for inserting and(or) updating multiple objects by providing an array of objects as an input. Please check [README](https://github.com/digitalnodecom/node-red-contrib-generic-s3/blob/main/README.md) for more detailed information. Also you can find the newest release on [npmjs.com](https://www.npmjs.com/package/@digitalnodecom/node-red-contrib-generic-s3). Feel free to open the issue if you think that the newest release does not address this.
