### ISSUE TITLE
Stop stripping the msg object from outputs

### ISSUE THREAD

**Issue by buroa** [digitalnodecom/node-red-contrib-generic-s3#37]
Seems like the output is only what it requested: https://github.com/digitalnodecom/node-red-contrib-generic-s3/blob/main/nodes/list-objects-v2/list-objects-v2.js#L98-L107

For this to work in a http-in flow, or many other examples, it needs to output the entire msg object as-is, otherwise we can't send a HTTP response back.

**Comment by rristov60** [comment]
Hi @buroa, sorry for the delayed reply, it was a busy period and I didn't have the time to work on this. Finally this will be patched. Thank you for opening this issue! You are raising a valid point, the output is modified as you have pointed out in the code, which won't integrate with other nodes well without additional modifications

**Comment by rristov60** [comment]
Hi @buroa, it took me a little bit more time than expected but this is finally patched in the newest version of the nodes, 1.7.2. As of now it is available to be updated on node-red. Thank you for the patience. Kind regards.
