### ISSUE TITLE
Put Object node typo in 'metadata' property

### ISSUE THREAD

**Issue by KIKOmanasijev** [digitalnodecom/node-red-contrib-generic-s3#38]
The "Put Object" node expects "metadata" property in order to update specific Object's metadata. There is a typo in the documentation, and this property has been written in camel case (`metaData`) - which results in setting the metadata of the targeted object to always be an empty object.

**Comment by rristov60** [comment]
Hi @KIKOmanasijev, thanks for opening an issue for this. This will be patched shortly

**Comment by rristov60** [comment]
@KIKOmanasijev this has been fixed and as of now it is available to update in node-red, version [1.7.3](https://www.npmjs.com/package/@digitalnodecom/node-red-contrib-generic-s3). Kind regards
