### ISSUE TITLE
Option to manually set 'contentEncoding' when doing Put or Copy Object

### ISSUE THREAD

**Issue by KIKOmanasijev** [digitalnodecom/node-red-contrib-generic-s3#44]
When doing a PutObject, there is a possibility to explicitly set the object's ContentType header via the msg.contentType property. It would be really handy if the same could be done for the ContentEncoding header - if possible - when creating, updating or copy-ing objects.

**Comment by rristov60** [comment]
Thanks for the issue @KIKOmanasijev, this feature will be implemented, and you will be notified once there is a new release closing this issue.

**Comment by rristov60** [comment]
@KIKOmanasijev, this feature has been added in the newest release [v1.10.0](https://github.com/digitalnodecom/node-red-contrib-generic-s3/releases/tag/v1.10.0) to _**Put Object**_, _**Put Objects**_, _**Copy Object**_ and _**Move Object**_ nodes. Feel free to reopen the issue if something pops up related to this or to open a new issue for another topic.
