### ISSUE TITLE
Typo in the readme, the npm package does not exist

### ISSUE THREAD

**Issue by KIKOmanasijev** [digitalnodecom/node-red-contrib-generic-s3#50]
According to the documentation, the command to install this package is:
`npm install node-red-contrib-generic-s3`

But this command returns 404 Not Found.

I've looked into your npmjs.com registry, and it seems like the command from above is missing your organisation prefix.
`npm i @digitalnodecom/node-red-contrib-generic-s3`

**Comment by rristov60** [comment]
Thanks for the issue @KIKOmanasijev. It looks like that has slipped from the beginning and it was never noticed. It will be fixed shortly
