### ISSUE TITLE
msg.bucket is ignored when using Create Bucket node

### ISSUE THREAD

**Issue by KIKOmanasijev** [digitalnodecom/node-red-contrib-generic-s3#69]
msg.bucket is ignored when using Create Bucket node. 

How to replicate:
- pass any value to msg.bucket, and it will be ignored. The GUI field is working properly though.

**Comment by KIKOmanasijev** [comment]
@rristov60 any updates on this?

**Comment by rristov60** [comment]
Hi @KIKOmanasijev, thanks for the issue! Currently looking into this, a fix is coming soon!

**Comment by rristov60** [comment]
@KIKOmanasijev, may I ask you which version you are using of the nodes, and what is the name of the bucket you are trying to create is following the naming conventions specified [here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html) ?

I tried to replicate the issue, but unfortunately I am not able to replicate this. I do get an `Invalid Bucket Name` error when trying to use bucket name that is not following the above mentioned convention.

Also please note that the priority is given to GUI field

**Comment by KIKOmanasijev** [comment]
@rristov60 Sorry for the late reply. It seems the issue was only available on my fork from this repo, and it's been fixed after pulling your latest changes. 

Therefore, I am closing this PR.
